version: "3"

services:
  redis:
    image: redis
  express:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=8000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:80"
